<?php
    include_once "ChiTietMay.php";
    class May extends ChiTietPhuc{
        protected $MaSoMay;
        protected $TenMay;

        public function GetMaMay(){
            return $this->MaSoMay;
        }

        public function Nhap()
        {
            do{
                $this->MaSoMay= Readline("Nhap Ma May:");
                $this->TenMay= Readline("Nhap Ten May:");
            }while($this->KTNULL($this->MaSoMay) != 1 || $this->KTNULL($this->TenMay) != 1);
            parent::Nhap();
        }

        public function Xuat()
        {
            echo "\n|| Ma So May: ".$this->MaSoMay;
            echo "\n|| Ten May: ". $this->TenMay."\n";
            parent::Xuat(); // TODO: Change the autogenerated stub
        }

        public function TinhGia()
        {
            return parent::TinhGia();
            return $this->TinhGia();
        }

        public function TinhKL()
        {
            return parent::TinhKL();
            return$this->TinhKL();
        }
    }
//$may = new May();
//$may->Nhap();
//$may->Xuat();
//$may->TinhGia();
//$may->TinhKL();
